### ISSUE TITLE
Domain build failure on large simulation

### ISSUE THREAD

**Issue by sbird** [MP-Gadget/MP-Gadget#429]
The 5500^3 Frontera run is failing on resume:

The error is:
 [ 000370.59 ] Task 0: toptree[162].Count=1, shift 0, last_leaf=162 key = 6020610249 i= 16 Nsample = 2563717

 Backtrace:
 Thread 1 (Thread 0x2b6f821b6880 (LWP 342611)):
     #0  0x00002b6f845f56fd in read () from /lib64/libpthread.so.0
     #1  0x0000000000465fbb in show_backtrace () at utils/endrun.c:78
     #2  endrun (where=77, fmt=0x7fff339f0800 "\001") at utils/endrun.c:159
     #3  0x000000000041c136 in domain_check_for_local_refine_subsample
     (policy=0x4d, topTree=0x7fff339f0800, topTreeSize=0xff, MaxTopNodes=-1)
     at domain.c:1011
     #4  0x0000000000419de4 in domain_determine_global_toptree (policy=0x4d,
     topTree=0x7fff339f0800, topTreeSize=0xff, MaxTopNodes=-1,
     DomainComm=14)
     at domain.c:1149
     #5  0x0000000000417df2 in domain_attempt_decompose (ddecomp=<optimized
     out>, policy=<optimized out>, MaxTopNodes=<optimized out>) at
     domain.c:353
     #6  domain_decompose_full (ddecomp=0x4d) at domain.c:181
     #7  0x000000000042effb in init (RestartSnapNum=1,
     ddecomp=0x7fff339f0800) at init.c:233
     #8  0x000000000042630b in run (RestartSnapNum=77) at run.c:161
     #9  0x0000000000409028 in main (argc=3, argv=0x7fff339f1298) at
     main.c:129
     Abort(10) on node 0 (rank 0 in comm 0): application called
     MPI_Abort(MPI_COMM_WORLD, 10) - process 0
     TACC:  MPI job exited with code: 10

**Comment by sbird** [comment]
Let's move to github issue:

https://github.com/MP-Gadget/MP-Gadget/issues/429

I think that we are at the beginning of the toptree build, and you may be right that these two particles are just in the same place for some reason.

I am wondering if the peano key is becoming degenerate because the box is just too big.

I think the fix though is easy in both cases: we should just not refine the node (and not fail) if the particles are in the same place. The likelihood that this significantly affects the particle balance is very small.

Simeon

**Comment by sbird** [comment]
We only have 21 levels in the Shift tree, and maybe we are just exhausting these before we do refinements. I think it doesn't matter though. The balance will just be a little wrong.

**Comment by sbird** [comment]
@yueyingn Can you see if that commit fixes the issue? Yu, review?
