### ISSUE TITLE
Getting  MPI_Abort(MPI_COMM_WORLD, 11) in basic DM only run.

### ISSUE THREAD

**Issue by Jravis** [MP-Gadget/MP-Gadget#470]
Hi all,
I have been using Gadget2 for my dm only runs and keen to learn MP-Gadget for hydro runs. To test basic installation I wanted to compare a small dm only run output using MP-Gadget and gadget2. I have used the same cosmological parameters and CAMB input and manage to run genic and generated ICs.

However, on running gadget it crash after loading particles, with the message
```
NuPartTime                      0.333333             # Default  # Scale factor at which to turn on hybrid neutrino particles.
[ 000000.00 ] ----------------------------------------------
[ 000000.00 ] Task 0: The Density Kernel type is QuinticSpline
[ 000000.00 ] Task 0: The Density resolution is 1 * mean separation, or 113.097 neighbours
[ 000000.01 ] Nhost = 1
[ 000000.01 ] Reserving 81144336384 bytes per rank for MAIN memory allocator. 
[ 000057.25 ] Aggregated IO is disabled.
[ 000057.25 ] Probing Header of snapshot file: output/IC
[ 000057.25 ] Total number of particles: 000000000002097152
[ 000057.25 ]         Gas: Total: 000000000000000000 Init: 000000000000000000 Mean-Sep 0 
[ 000057.25 ]  DarkMatter: Total: 000000000002097152 Init: 000000000002097152 Mean-Sep 3906.25
[ 000057.25 ]    Neutrino: Total: 000000000000000000 Init: 000000000000000000 Mean-Sep 0
[ 000057.25 ]     Unknown: Total: 000000000000000000 Init: 000000000000000000 Mean-Sep 0
[ 000057.25 ]        Star: Total: 000000000000000000 Init: 000000000000000000 Mean-Sep 0
[ 000057.25 ]   BlackHole: Total: 000000000000000000 Init: 000000000000000000 Mean-Sep 0
[ 000057.25 ] Hubble (internal units) = 0.1
[ 000057.25 ] G (internal units) = 43007.1
[ 000057.25 ] UnitLength_in_cm = 3.08568e+21
[ 000057.25 ] UnitMass_in_g = 1.989e+43
[ 000057.25 ] UnitTime_in_s = 3.08568e+16
[ 000057.25 ] UnitVelocity_in_cm_per_s = 100000
[ 000057.25 ] UnitDensity_in_cgs = 6.76991e-22
[ 000057.25 ] UnitEnergy_in_cgs = 1.989e+53
[ 000057.25 ] Dark energy model: OmegaL = 0.7186 OmegaFLD = 0
[ 000057.25 ] Photon density OmegaG = 5.08867e-05
[ 000057.25 ] Massless Neutrino density OmegaNu0 = 3.51275e-05
[ 000057.25 ] Curvature density OmegaK = 0
[ 000057.25 ] Radiation is enabled in Hubble(a). Following CAMB convention: Omega_Tot - 1 = 8.60142e-05
[ 000057.25 ]
[ 000057.25 ] GravitySoftening = 130.208
[ 000057.25 ] Using 2D Task mesh 2 x 2
[ 000057.26 ] Initial TimeStep at TimeInit 0.01 Ti_Current = 0
Killed by Signal 11
Killed by Signal 11
Killed by Signal 11
Killed by Signal 11
Thread 2 (Thread 0x7fba3a958700 (LWP 18780)):
#0  futex_wait (val=24, addr=0x178ee24) at ../.././libgomp/config/linux/x86/futex.h:44
#1  do_wait (val=24, addr=0x178ee24) at ../.././libgomp/config/linux/wait.h:67
#2  do_wait (val=24, addr=0x178ee24) at ../.././libgomp/config/linux/wait.h:64
#3  gomp_barrier_wait_end (bar=0x178ee20, state=24) at ../.././libgomp/config/linux/bar.c:48
#4  0x00007fcd23074ec0 in gomp_simple_barrier_wait (bar=0x178ee20) at ../.././libgomp/config/posix/simple-bar.h:60
#5  gomp_thread_start (xdata=<optimized out>) at ../.././libgomp/team.c:127
#6  0x00007fcd22e46dc5 in start_thread () from /lib64/libpthread.so.0
#7  0x00007fcd22b7573d in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7fcd24302bc0 (LWP 18762)):
#0  0x00007fcd22e4d49d in read () from /lib64/libpthread.so.0
#1  0x00000000004466c1 in show_backtrace () at utils/endrun.c:78
#2  0x000000000044690d in OsSigHandler (no=11) at utils/endrun.c:111
#3  <signal handler called>
#4  get_photo_rate (Gamma_tab=<optimized out>, Gamma_tab=<optimized out>, redshift=98.999999999999957) at cooling_rates.c:221
#5  get_photo_rate (Gamma_tab=0x7c4a60 <Gamma_HI>, Gamma_tab=0x7c4a60 <Gamma_HI>, redshift=98.999999999999957) at cooling_rates.c:215
#6  get_global_UVBG (redshift=redshift@entry=98.999999999999957) at cooling_rates.c:274
#7  0x000000000042d114 in set_global_uvbg (redshift=98.999999999999957) at cooling_uvfluc.c:32
#8  0x00000000004211da in set_global_time (Ti_Current=<optimized out>) at timestep.c:175
#9  0x000000000042372f in init (RestartSnapNum=RestartSnapNum@entry=-1, ddecomp=ddecomp@entry=0x7ffd708b2bb0) at init.c:169
#10 0x000000000041d550 in run (RestartSnapNum=-1) at run.c:161
#11 0x0000000000404752 in main (argc=<optimized out>, argv=<optimized out>) at main.c:129
               
```                                                                      
I have also tried the examples for dm only run with default parameters and facing the same issues.

I am using our local machine with 512 GB ram and 32 cores, for compile I have used mpich-3.2, gcc 9.2 and gsl 2.6.

Looking forward to hearing from you.

**Comment by sbird** [comment]
Thanks for the report! Should be fixed in the master branch. By the way, I haven't seen your parameter file but to get good results for  hydro run you probably want to enable cooling with CoolingOn = 1 and supply a TREECOOL file.
